/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  SentimentAnalysis as PrismaSentimentAnalysis,
} from "@prisma/client";

export class SentimentAnalysisServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SentimentAnalysisCountArgs, "select">
  ): Promise<number> {
    return this.prisma.sentimentAnalysis.count(args);
  }

  async sentimentAnalyses<T extends Prisma.SentimentAnalysisFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.SentimentAnalysisFindManyArgs>
  ): Promise<PrismaSentimentAnalysis[]> {
    return this.prisma.sentimentAnalysis.findMany<Prisma.SentimentAnalysisFindManyArgs>(
      args
    );
  }
  async sentimentAnalysis<T extends Prisma.SentimentAnalysisFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.SentimentAnalysisFindUniqueArgs>
  ): Promise<PrismaSentimentAnalysis | null> {
    return this.prisma.sentimentAnalysis.findUnique(args);
  }
  async createSentimentAnalysis<T extends Prisma.SentimentAnalysisCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SentimentAnalysisCreateArgs>
  ): Promise<PrismaSentimentAnalysis> {
    return this.prisma.sentimentAnalysis.create<T>(args);
  }
  async updateSentimentAnalysis<T extends Prisma.SentimentAnalysisUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SentimentAnalysisUpdateArgs>
  ): Promise<PrismaSentimentAnalysis> {
    return this.prisma.sentimentAnalysis.update<T>(args);
  }
  async deleteSentimentAnalysis<T extends Prisma.SentimentAnalysisDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.SentimentAnalysisDeleteArgs>
  ): Promise<PrismaSentimentAnalysis> {
    return this.prisma.sentimentAnalysis.delete(args);
  }
}
